//! End-to-end SIMD/scalar differential coverage over generated, conformant VP9 streams.
//!
//! `simd::avx2_enabled()` caches both the CPU feature probe and `VP9DEC_NO_SIMD` in a
//! `OnceLock`, so changing the environment inside one test process cannot reliably select
//! both implementations. The parent test therefore starts this integration-test binary twice:
//! once with `VP9DEC_NO_SIMD` removed and once with it set. Each child verifies the selected
//! dispatch mode before decoding the same deterministic scenarios.
//!
//! Generation is syntax-aware, not byte mutation:
//!
//! - profile/bit-depth/subsampling values come from an explicitly valid table;
//! - modes, segmentation levels, loop-filter levels, and probabilities are selected only
//!   from their legal ranges;
//! - every coded block is lossless and skipped, so no coefficient token is present (and the
//!   malformed-coefficient SIMD/scalar wrap caveat cannot apply);
//! - the generated scaled-reference case uses the spec §8.5.2.3 maximum conformant ratio,
//!   exactly 2x, never a malformed ratio.
//!
//! The report contains both the generated bytes and every decoded output sample. Comparing the
//! reports byte-for-byte therefore checks the inputs were identical as well as the outputs.

mod common;

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use common::encoder::{
    assemble_frame, build_inter_compressed_header, build_inter_header,
    build_keyframe_compressed_header, build_keyframe_header, build_keyframe_header_with_config,
    encode_keyframe_tile, encode_tree, header_size, kb, KeyframeConfig, SegSpec,
};
use vp9dec::header::{SEG_LVL_ALT_L, SEG_LVL_REF_FRAME, SEG_LVL_SKIP};
use vp9dec::prob_tables::{
    D117_PRED, D135_PRED, D153_PRED, D207_PRED, D45_PRED, D63_PRED, DC_PRED,
    DEFAULT_PARTITION_PROBS, DEFAULT_SKIP_PROB, H_PRED, INTRA_MODE_TREE, KF_PARTITION_PROBS,
    KF_UV_MODE_PROBS, KF_Y_MODE_PROBS, LAST_FRAME, PARTITION_NONE, PARTITION_TREE, TM_PRED, V_PRED,
};
use vp9dec::test_support::BoolEncoder;
use vp9dec::{DecodedFrame, Decoder, Frame, FrameDecodeInfo, PlaneData};

const CHILD_OUTPUT_ENV: &str = "VP9DEC_DIFF_CHILD_OUTPUT";
const CHILD_MODE_ENV: &str = "VP9DEC_DIFF_CHILD_MODE";
const REPORT_MAGIC: &[u8; 8] = b"VPDIF001";
const SMALL_SCENARIOS: usize = 24;
const EXPECTED_SCENARIOS: usize = SMALL_SCENARIOS + 3;

const INTRA_MODES: [u8; 10] = [
    DC_PRED, V_PRED, H_PRED, D45_PRED, D135_PRED, D117_PRED, D153_PRED, D207_PRED, D63_PRED,
    TM_PRED,
];

#[derive(Clone, Copy)]
struct Format {
    profile: u8,
    bit_depth: u8,
    subsampling_x: u8,
    subsampling_y: u8,
}

// Profiles 0/2 are 4:2:0. Profiles 1/3 deliberately cover each non-4:2:0 YUV layout.
const FORMATS: [Format; 10] = [
    Format {
        profile: 0,
        bit_depth: 8,
        subsampling_x: 1,
        subsampling_y: 1,
    },
    Format {
        profile: 1,
        bit_depth: 8,
        subsampling_x: 0,
        subsampling_y: 0,
    },
    Format {
        profile: 1,
        bit_depth: 8,
        subsampling_x: 1,
        subsampling_y: 0,
    },
    Format {
        profile: 1,
        bit_depth: 8,
        subsampling_x: 0,
        subsampling_y: 1,
    },
    Format {
        profile: 2,
        bit_depth: 10,
        subsampling_x: 1,
        subsampling_y: 1,
    },
    Format {
        profile: 2,
        bit_depth: 12,
        subsampling_x: 1,
        subsampling_y: 1,
    },
    Format {
        profile: 3,
        bit_depth: 10,
        subsampling_x: 0,
        subsampling_y: 0,
    },
    Format {
        profile: 3,
        bit_depth: 10,
        subsampling_x: 1,
        subsampling_y: 0,
    },
    Format {
        profile: 3,
        bit_depth: 12,
        subsampling_x: 0,
        subsampling_y: 1,
    },
    Format {
        profile: 3,
        bit_depth: 12,
        subsampling_x: 0,
        subsampling_y: 0,
    },
];

struct Scenario {
    name: String,
    chunks: Vec<Vec<u8>>,
}

/// Small deterministic selector. Its output never becomes raw bitstream bytes; it only indexes
/// the legal tables/ranges above, which keeps every generated stream conformant by construction.
struct Selector(u64);

impl Selector {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x as u32
    }

    fn index(&mut self, len: usize) -> usize {
        self.next() as usize % len
    }
}

fn build_small_keyframe(index: usize, selector: &mut Selector) -> Scenario {
    let format = FORMATS[index % FORMATS.len()];
    let segmented = !index.is_multiple_of(3);
    let segmentation = if segmented {
        let mut seg = SegSpec::enabled();
        seg.abs_or_delta_update = true;
        seg.feature_enabled[1][SEG_LVL_ALT_L] = true;
        seg.feature_data[1][SEG_LVL_ALT_L] = (selector.next() % 64) as i32;
        for probability in &mut seg.tree_probs {
            // Stay comfortably away from the arithmetic coder's degenerate endpoints.
            *probability = 64 + (selector.next() % 129) as u8;
        }
        seg
    } else {
        SegSpec::disabled()
    };

    // Ensure generated segmented cases contain both segment 0 and segment 1.
    let first_segment = usize::from(segmented && index.is_multiple_of(2)) as u8;
    let segment_ids = [
        first_segment,
        u8::from(segmented) - first_segment,
        u8::from(segmented && selector.next().is_multiple_of(2)),
        u8::from(segmented && selector.next().is_multiple_of(2)),
    ];
    let blocks = std::array::from_fn(|block| {
        kb(
            segmented.then_some(segment_ids[block]),
            INTRA_MODES[selector.index(INTRA_MODES.len())],
        )
    });

    let compressed = build_keyframe_compressed_header();
    let loop_filter_level = if index.is_multiple_of(5) {
        0
    } else {
        1 + (selector.next() % 63) as u8
    };
    let header = build_keyframe_header_with_config(
        16,
        16,
        loop_filter_level,
        index.is_multiple_of(2),
        &segmentation,
        header_size(&compressed),
        KeyframeConfig {
            profile: format.profile,
            bit_depth: format.bit_depth,
            subsampling_x: format.subsampling_x,
            subsampling_y: format.subsampling_y,
            tile_cols_log2: 0,
        },
    );
    let tile = encode_keyframe_tile(blocks, segmentation.tree_probs);

    Scenario {
        name: format!(
            "small-{index:02}-p{}-{}bit-{}{}-seg{}-lf{loop_filter_level}",
            format.profile,
            format.bit_depth,
            format.subsampling_x,
            format.subsampling_y,
            u8::from(segmented),
        ),
        chunks: vec![assemble_frame(header, compressed, tile)],
    }
}

/// One 256x64 tile made of four lossless, skipped 64x64 intra blocks.
fn encode_uniform_wide_tile(mode: u8) -> Vec<u8> {
    let mut enc = BoolEncoder::new();
    for sb_col in 0..4 {
        encode_tree(&mut enc, &PARTITION_TREE, PARTITION_NONE, |node| {
            KF_PARTITION_PROBS[12][node]
        });
        enc.write_bool(true, DEFAULT_SKIP_PROB[usize::from(sb_col != 0)]);
        let left_mode = if sb_col == 0 { DC_PRED } else { mode };
        encode_tree(&mut enc, &INTRA_MODE_TREE, mode, |node| {
            KF_Y_MODE_PROBS[DC_PRED as usize][left_mode as usize][node]
        });
        encode_tree(&mut enc, &INTRA_MODE_TREE, mode, |node| {
            KF_UV_MODE_PROBS[mode as usize][node]
        });
    }
    enc.finish()
}

fn build_wide_tiled_keyframe(name: &str, format: Format) -> Scenario {
    let compressed = build_keyframe_compressed_header();
    let header = build_keyframe_header_with_config(
        512,
        64,
        63,
        false,
        &SegSpec::disabled(),
        header_size(&compressed),
        KeyframeConfig {
            profile: format.profile,
            bit_depth: format.bit_depth,
            subsampling_x: format.subsampling_x,
            subsampling_y: format.subsampling_y,
            tile_cols_log2: 1,
        },
    );

    let mut left = encode_uniform_wide_tile(V_PRED);
    let mut right = encode_uniform_wide_tile(H_PRED);
    // Keep explicit zero tail bytes within each declared bool-coded tile. They are valid
    // padding and prevent an external-style strict reader from treating range finalization as
    // truncation.
    left.extend_from_slice(&[0; 4]);
    right.extend_from_slice(&[0; 4]);
    let mut tiles = Vec::with_capacity(4 + left.len() + right.len());
    tiles.extend_from_slice(
        &u32::try_from(left.len())
            .expect("generated tile length fits u32")
            .to_be_bytes(),
    );
    tiles.extend_from_slice(&left);
    tiles.extend_from_slice(&right);

    Scenario {
        name: name.to_string(),
        chunks: vec![assemble_frame(header, compressed, tiles)],
    }
}

/// A 64-wide keyframe tile with `sb_rows` complete 64x64 DC/skip superblocks.
fn encode_scaled_reference_keyframe_tile(sb_rows: usize) -> Vec<u8> {
    let mut enc = BoolEncoder::new();
    for sb_row in 0..sb_rows {
        encode_tree(&mut enc, &PARTITION_TREE, PARTITION_NONE, |node| {
            KF_PARTITION_PROBS[12][node]
        });
        enc.write_bool(true, DEFAULT_SKIP_PROB[usize::from(sb_row != 0)]);
        encode_tree(&mut enc, &INTRA_MODE_TREE, DC_PRED, |node| {
            KF_Y_MODE_PROBS[DC_PRED as usize][DC_PRED as usize][node]
        });
        encode_tree(&mut enc, &INTRA_MODE_TREE, DC_PRED, |node| {
            KF_UV_MODE_PROBS[DC_PRED as usize][node]
        });
    }
    enc.finish()
}

fn build_scaled_reference_scenario() -> Scenario {
    let key_compressed = build_keyframe_compressed_header();
    let key_header = build_keyframe_header(
        64,
        128,
        0,
        false,
        &SegSpec::disabled(),
        header_size(&key_compressed),
    );
    let key_tile = encode_scaled_reference_keyframe_tile(2);
    let keyframe = assemble_frame(key_header, key_compressed, key_tile);

    // Segment 0 forces LAST + ZEROMV + skip. The single inter tile therefore contains only
    // its PARTITION_NONE symbol while still running the full 2x scaled prediction path.
    let mut segmentation = SegSpec {
        enabled: true,
        update_map: false,
        update_data: true,
        ..SegSpec::disabled()
    };
    segmentation.feature_enabled[0][SEG_LVL_REF_FRAME] = true;
    segmentation.feature_data[0][SEG_LVL_REF_FRAME] = LAST_FRAME as i32;
    segmentation.feature_enabled[0][SEG_LVL_SKIP] = true;

    let inter_compressed = build_inter_compressed_header();
    let inter_header = build_inter_header(
        [0, 0, 0],
        Some((64, 64)),
        0,
        &segmentation,
        header_size(&inter_compressed),
    );
    let mut inter_tile = BoolEncoder::new();
    encode_tree(&mut inter_tile, &PARTITION_TREE, PARTITION_NONE, |node| {
        DEFAULT_PARTITION_PROBS[12][node]
    });
    let inter = assemble_frame(inter_header, inter_compressed, inter_tile.finish());

    Scenario {
        name: "scaled-2x-last-reference".to_string(),
        chunks: vec![keyframe, inter],
    }
}

fn conformant_scenarios() -> Vec<Scenario> {
    let mut selector = Selector::new(0x6a09_e667_f3bc_c909);
    let mut scenarios = Vec::with_capacity(EXPECTED_SCENARIOS);
    for index in 0..SMALL_SCENARIOS {
        scenarios.push(build_small_keyframe(index, &mut selector));
    }
    scenarios.push(build_wide_tiled_keyframe(
        "wide-p3-10bit-444-two-tiles",
        Format {
            profile: 3,
            bit_depth: 10,
            subsampling_x: 0,
            subsampling_y: 0,
        },
    ));
    scenarios.push(build_wide_tiled_keyframe(
        "wide-p2-12bit-420-two-tiles",
        Format {
            profile: 2,
            bit_depth: 12,
            subsampling_x: 1,
            subsampling_y: 1,
        },
    ));
    scenarios.push(build_scaled_reference_scenario());
    assert_eq!(
        scenarios.len(),
        EXPECTED_SCENARIOS,
        "differential corpus must never become empty or silently lose a scenario"
    );
    scenarios
}

fn push_u32(report: &mut Vec<u8>, value: usize) {
    report.extend_from_slice(
        &u32::try_from(value)
            .expect("generated report field fits u32")
            .to_le_bytes(),
    );
}

fn push_bytes(report: &mut Vec<u8>, bytes: &[u8]) {
    push_u32(report, bytes.len());
    report.extend_from_slice(bytes);
}

fn push_info(report: &mut Vec<u8>, info: Option<FrameDecodeInfo>) {
    let Some(info) = info else {
        report.push(0);
        return;
    };
    report.push(1);
    report.push(u8::from(info.intra_only));
    report.push(u8::from(info.frame_is_intra));
    report.push(info.reset_frame_context);
    report.push(u8::from(info.segmentation_enabled));
    report.extend(info.seg_features_active.map(u8::from));
}

fn push_plane(report: &mut Vec<u8>, plane: &PlaneData) {
    match plane {
        PlaneData::U8(samples) => {
            report.push(8);
            push_bytes(report, samples);
        }
        PlaneData::U16(samples) => {
            report.push(16);
            push_u32(report, samples.len());
            for &sample in samples {
                report.extend_from_slice(&sample.to_le_bytes());
            }
        }
    }
}

fn push_frame(report: &mut Vec<u8>, frame: Option<&Frame>) {
    let Some(frame) = frame else {
        report.push(0);
        return;
    };
    report.push(1);
    report.extend_from_slice(&frame.width.to_le_bytes());
    report.extend_from_slice(&frame.height.to_le_bytes());
    report.push(frame.bit_depth);
    report.extend_from_slice(&frame.subsampling_x.to_le_bytes());
    report.extend_from_slice(&frame.subsampling_y.to_le_bytes());
    push_plane(report, &frame.y);
    push_plane(report, &frame.u);
    push_plane(report, &frame.v);
}

fn push_decoded(report: &mut Vec<u8>, decoded: &[DecodedFrame]) {
    push_u32(report, decoded.len());
    for output in decoded {
        push_info(report, output.info);
        push_frame(report, output.frame.as_ref());
    }
}

fn generate_report() -> Vec<u8> {
    let scenarios = conformant_scenarios();
    let mut report = Vec::new();
    report.extend_from_slice(REPORT_MAGIC);
    push_u32(&mut report, scenarios.len());

    for scenario in scenarios {
        push_bytes(&mut report, scenario.name.as_bytes());
        push_u32(&mut report, scenario.chunks.len());
        let mut decoder = Decoder::new();
        for chunk in scenario.chunks {
            push_bytes(&mut report, &chunk);
            let decoded = decoder
                .decode_frame(&chunk)
                .unwrap_or_else(|error| panic!("{} must decode: {error:?}", scenario.name));
            push_decoded(&mut report, &decoded);
        }
    }
    report
}

/// Internal subprocess entry point. Ignored in an ordinary harness run; the parent test invokes
/// it explicitly with `--ignored --exact` after fixing the environment for the whole process.
#[test]
#[ignore = "internal child process for generated_streams_match_with_simd_and_forced_scalar"]
fn generated_streams_decode_child() {
    let Some(output_path) = std::env::var_os(CHILD_OUTPUT_ENV) else {
        eprintln!("[skip] {CHILD_OUTPUT_ENV} is only set by the differential parent test");
        return;
    };
    let mode = std::env::var(CHILD_MODE_ENV).expect("differential child mode must be set");
    #[cfg(target_arch = "x86_64")]
    let enabled = vp9dec::simd::avx2_enabled();
    #[cfg(not(target_arch = "x86_64"))]
    let enabled = false;
    match mode.as_str() {
        "simd" => assert!(
            enabled,
            "SIMD child did not select AVX2; process isolation/env setup is ineffective"
        ),
        "scalar" => assert!(
            !enabled,
            "scalar child did not honor VP9DEC_NO_SIMD before the OnceLock probe"
        ),
        other => panic!("unknown differential child mode {other:?}"),
    }

    let report = generate_report();
    std::fs::write(&output_path, &report).unwrap_or_else(|error| {
        panic!(
            "write differential report {}: {error}",
            Path::new(&output_path).display()
        )
    });
    eprintln!(
        "[diff-child] mode={mode} scenarios={EXPECTED_SCENARIOS} report_bytes={}",
        report.len()
    );
}

struct RemoveFiles([PathBuf; 2]);

impl Drop for RemoveFiles {
    fn drop(&mut self) {
        for path in &self.0 {
            let _ = std::fs::remove_file(path);
        }
    }
}

fn run_child(mode: &str, report_path: &Path) -> Output {
    let mut command =
        Command::new(std::env::current_exe().expect("locate integration-test binary"));
    command
        .arg("generated_streams_decode_child")
        .arg("--exact")
        .arg("--ignored")
        .arg("--nocapture")
        .env(CHILD_MODE_ENV, mode)
        .env(CHILD_OUTPUT_ENV, report_path);
    if mode == "scalar" {
        command.env("VP9DEC_NO_SIMD", "1");
    } else {
        // Also overrides a caller running the outer suite under VP9DEC_NO_SIMD=1.
        command.env_remove("VP9DEC_NO_SIMD");
    }
    command.output().expect("run differential child process")
}

fn assert_child_succeeded(mode: &str, output: &Output) {
    assert!(
        output.status.success(),
        "{mode} child failed with {}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

fn scenario_count(report: &[u8]) -> usize {
    assert!(
        report.len() >= REPORT_MAGIC.len() + 4,
        "differential report is truncated"
    );
    assert_eq!(&report[..REPORT_MAGIC.len()], REPORT_MAGIC);
    u32::from_le_bytes(
        report[REPORT_MAGIC.len()..REPORT_MAGIC.len() + 4]
            .try_into()
            .unwrap(),
    ) as usize
}

fn first_difference(left: &[u8], right: &[u8]) -> Option<usize> {
    left.iter()
        .zip(right)
        .position(|(left, right)| left != right)
        .or_else(|| (left.len() != right.len()).then_some(left.len().min(right.len())))
}

#[test]
fn generated_streams_match_with_simd_and_forced_scalar() {
    #[cfg(not(target_arch = "x86_64"))]
    {
        eprintln!("[skip] generated SIMD/scalar differential test requires x86_64 AVX2");
        return;
    }
    #[cfg(target_arch = "x86_64")]
    if !is_x86_feature_detected!("avx2") {
        eprintln!("[skip] generated SIMD/scalar differential test requires an AVX2 CPU");
        return;
    }

    let stem = format!("vp9dec_diff_{}", std::process::id());
    let simd_path = std::env::temp_dir().join(format!("{stem}_simd.bin"));
    let scalar_path = std::env::temp_dir().join(format!("{stem}_scalar.bin"));
    let _cleanup = RemoveFiles([simd_path.clone(), scalar_path.clone()]);
    // Stale files cannot turn a child that forgot to write its report into a false pass.
    for path in [&simd_path, &scalar_path] {
        if path.exists() {
            std::fs::remove_file(path)
                .unwrap_or_else(|error| panic!("remove stale report {}: {error}", path.display()));
        }
    }

    let simd_output = run_child("simd", &simd_path);
    assert_child_succeeded("SIMD", &simd_output);
    let scalar_output = run_child("scalar", &scalar_path);
    assert_child_succeeded("forced-scalar", &scalar_output);

    let simd_report = std::fs::read(&simd_path).expect("read SIMD differential report");
    let scalar_report = std::fs::read(&scalar_path).expect("read scalar differential report");
    let simd_count = scenario_count(&simd_report);
    let scalar_count = scenario_count(&scalar_report);
    assert_eq!(simd_count, EXPECTED_SCENARIOS);
    assert_eq!(scalar_count, EXPECTED_SCENARIOS);
    assert!(
        simd_count > 0,
        "differential comparison must be non-vacuous"
    );

    if let Some(offset) = first_difference(&simd_report, &scalar_report) {
        panic!(
            "SIMD/scalar report mismatch at byte {offset} (SIMD len {}, scalar len {}); \
             both children decoded {simd_count} conformant generated scenarios",
            simd_report.len(),
            scalar_report.len()
        );
    }
    eprintln!(
        "[diff] {simd_count} conformant generated scenarios matched; report_bytes={}",
        simd_report.len()
    );
}
